# Generated by Django 4.2.4 on 2023-08-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='combo',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
