# Generated by Django 3.2 on 2023-08-18 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_set', to='task_account.group'),
        ),
    ]
