# Generated by Django 3.2 on 2023-08-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
