# Generated by Django 3.2 on 2023-08-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
