# Generated by Django 4.2.4 on 2023-08-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='end',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='high',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='low',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
