# Generated by Django 4.2.4 on 2023-08-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tzinfo',
            field=models.CharField(default='Asia/Seoul', max_length=50),
        ),
    ]
