# Generated by Django 4.2.4 on 2023-08-14 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='my_group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
