# Generated by Django 4.2.4 on 2023-08-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tzinfo',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
