# Generated by Django 3.2 on 2023-08-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='password',
        ),
        migrations.AddField(
            model_name='group',
            name='delta',
            field=models.IntegerField(default=0),
        ),
    ]
