# Generated by Django 4.2.4 on 2023-08-15 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0002_remove_user_my_group_delete_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('create_user', models.CharField(default='', max_length=30)),
                ('price', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='my_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_set', to='task_account.group'),
        ),
    ]
