# Generated by Django 3.2 on 2023-08-18 11:50

from django.db import migrations
def add_initial_badges(apps, schema_editor):
    Badge = apps.get_model('task_account', 'Badge')
    
    badge_data = [('Rising Star', '첫 가치 상승')]
    
    for name, description in badge_data:
        Badge.objects.create(name=name, description=description)

class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0002_auto_20230818_2048'),
    ]

    operations = [
        migrations.RunPython(add_initial_badges),
    ]
