# Generated by Django 4.2.4 on 2023-08-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0002_group_user_my_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='create_user',
            field=models.CharField(default='', max_length=30),
        ),
    ]
