# Generated by Django 4.2.4 on 2023-08-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0002_user_combo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='combo',
        ),
    ]
