# Generated by Django 3.2 on 2023-08-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0002_auto_20230816_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='todo_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
