# Generated by Django 4.2.4 on 2023-08-05 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0002_remove_todo_created_time_todo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 11, 50, 54, 150600, tzinfo=datetime.timezone.utc)),
        ),
    ]
