# Generated by Django 4.2.4 on 2023-08-15 13:17

from django.db import migrations

def add_initial_badges(apps, schema_editor):
    Badge = apps.get_model('task_account', 'Badge')
    
    badge_names = ['지금이라도 사야해', '개미의 선택', '슈퍼 개미의 선택', '우주 개미의 선택', '콩콩', '1+1', '급등주']
    for name in badge_names:
        Badge.objects.create(name=name)
    

class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0002_badge_name'),
    ]

    operations = [
        migrations.RunPython(add_initial_badges),
    ]
