# Generated by Django 4.2.4 on 2023-08-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0002_user_tzinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='finish_time',
            new_name='finish_at',
        ),
    ]
