# Generated by Django 4.2.4 on 2023-08-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0002_alter_value_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='date',
            field=models.DateField(),
        ),
    ]
