# Generated by Django 4.2.4 on 2023-08-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0002_remove_todo_todolist_todo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='goal_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='level',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
