# Generated by Django 3.2 on 2023-08-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0003_user_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users_last_updated',
            field=models.JSONField(default=dict),
        ),
    ]
