# Generated by Django 3.2 on 2023-08-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0003_auto_20230816_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_active',
            field=models.BooleanField(default=False),
        ),
    ]
