from django.db import migrations

def add_initial_badges(apps, schema_editor):
    Badge = apps.get_model('task_account', 'Badge')
    
    badge_names = ['지금이라도 사야해', '개미의 선택', '슈퍼 개미의 선택', '우주 개미의 선택', '콩콩', '1+1', '급등주']
    for name in badge_names:
        Badge.objects.create(name=name)
    

class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0003_auto_20230815_2217'),
    ]

    operations = [
        migrations.RunPython(add_initial_badges),
    ]


























# # Generated by Django 4.2.4 on 2023-08-15 14:48

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('task_account', '0003_auto_20230815_2217'),
#     ]

#     operations = [
#     ]
