# Generated by Django 4.2.4 on 2023-08-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0003_alter_group_create_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to='task_account.group'),
        ),
    ]
