# Generated by Django 3.2 on 2023-08-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0003_group_user_my_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
