# Generated by Django 4.2.4 on 2023-08-11 09:37

from django.db import migrations, models
import server.apps.task_account.models


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0003_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=server.apps.task_account.models.user_directory_path),
        ),
    ]
