# Generated by Django 4.2.4 on 2023-08-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0003_category_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='memory',
            field=models.TextField(null=True),
        ),
    ]
