# Generated by Django 4.2.4 on 2023-08-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0004_alter_category_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
