# Generated by Django 3.2 on 2023-08-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_account', '0004_group_users_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='users_last_updated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='earning',
        ),
    ]
